package demo.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import javax.annotation.security.RolesAllowed;

import demo.demo.model.*;
import demo.demo.repository.RegisterRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/register") // This means URL's start with /demo (after Application path)
public class RegisterController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private RegisterRepository Repository;

  @RolesAllowed({"USER","ADMIN"})
  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String RegisterStudent(@ModelAttribute Register register, Model model) {
    model.addAttribute("register", register);
    Repository.save(register);
    return "Submitted";
  }

  @RolesAllowed({"USER","ADMIN"})
  @GetMapping(path="/add")
  public @ResponseBody String RegisterForm(Model model) {
    model.addAttribute("register", new Register());
    return "Register";
  }

  @RolesAllowed("ADMIN")
  @GetMapping(path="/view")
  public @ResponseBody Iterable<Register> getAllUsers() {
    // This returns a JSON or XML with the users
    return Repository.findAll();
  }
}
