package demo.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import javax.annotation.security.RolesAllowed;

import demo.demo.model.*;
import demo.demo.service.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/register") // This means URL's start with /demo (after Application path)
public class RegisterController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
         private StudentService studentService;

  @GetMapping({"/",""})
  public String getStudentForm(Model model) {
      // create model attribute to bind form data
      model.addAttribute("student", new Student());
      return "StudentForm";
  }

  @RolesAllowed({"USER","ADMIN"})
  @PostMapping(path="/add") // Map ONLY POST Requests
  public String RegisterStudent(@ModelAttribute("student") Student student) {
    studentService.saveStudent(student);
    return "Submitted";
  }
}
