package demo.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import javax.annotation.security.RolesAllowed;

import demo.demo.model.*;
import demo.demo.repository.StudentRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/students") // This means URL's start with /demo (after Application path)
public class StudentController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private StudentRepository Repository;

  @RolesAllowed("ADMIN")
  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String StudentSubmit (@ModelAttribute Student student, Model model) {
    model.addAttribute("student", student);
    Repository.save(student);
    return "Submitted";
  }

  @RolesAllowed("ADMIN")
  @GetMapping(path="/add")
  public @ResponseBody String StudentForm(Model model) {
    model.addAttribute("student", new Student());
    return "Student";
  }

  @RolesAllowed("ADMIN")
  @GetMapping(path="/view")
  public @ResponseBody Iterable<Student> getAllUsers() {
    // This returns a JSON or XML with the users
    return Repository.findAll();
  }
}